FROM python:3.11-slim
WORKDIR /app

COPY movie-backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY movie-backend/service.py ./service.py
COPY finetuned_embedding ./finetuned_embedding

EXPOSE 5000
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "service:app"]
