FROM node:18-alpine
WORKDIR /app

COPY movie-backend/package*.json ./
RUN npm ci --only=production

COPY movie-backend/server.js ./
COPY movie-backend/configs ./configs

EXPOSE 3000
CMD ["node", "server.js"]
